import 'package:flutter/foundation.dart';
import '../models/identity.dart';
import 'core_bridge.dart';

/// Service for identity management.
///
/// Delegates all key generation, storage, and cryptographic
/// operations to the Python core. This service only manages
/// the UI-facing state.
class IdentityService extends ChangeNotifier {
  final CoreBridge _bridge;

  Identity _identity = Identity.empty();
  Identity get identity => _identity;

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  String? _error;
  String? get error => _error;

  IdentityService(this._bridge);

  /// Generate a new Ed25519 identity keypair.
  ///
  /// WARNING: The seed is generated by the core using CSPRNG.
  /// The user MUST save their seed. There is no recovery mechanism.
  Future<bool> generateIdentity({required String passphrase}) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    final response = await _bridge.send(
      method: 'generate_identity',
      params: {'passphrase': passphrase},
    );

    _isLoading = false;

    if (response.success && response.result != null) {
      _identity = Identity.fromJson(response.result!);
      notifyListeners();
      return true;
    }

    _error = response.error ?? 'Failed to generate identity';
    notifyListeners();
    return false;
  }

  /// Load an existing identity from the encrypted keystore.
  Future<bool> loadIdentity({required String passphrase}) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    final response = await _bridge.send(
      method: 'load_identity',
      params: {'passphrase': passphrase},
    );

    _isLoading = false;

    if (response.success && response.result != null) {
      _identity = Identity.fromJson(response.result!);
      notifyListeners();
      return true;
    }

    _error = response.error ?? 'Failed to load identity';
    notifyListeners();
    return false;
  }

  /// Export identity data for sharing (public key + onion address).
  ///
  /// Only the public portion is exported. Private keys never
  /// leave the Python core process.
  Future<String?> exportIdentity() async {
    final response = await _bridge.send(method: 'export_identity');

    if (response.success && response.result != null) {
      return response.result!['export_data'] as String?;
    }

    _error = response.error ?? 'Failed to export identity';
    notifyListeners();
    return null;
  }

  /// Import an identity from exported data.
  Future<bool> importIdentity({
    required String importData,
    required String passphrase,
  }) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    final response = await _bridge.send(
      method: 'import_identity',
      params: {
        'import_data': importData,
        'passphrase': passphrase,
      },
    );

    _isLoading = false;

    if (response.success && response.result != null) {
      _identity = Identity.fromJson(response.result!);
      notifyListeners();
      return true;
    }

    _error = response.error ?? 'Failed to import identity';
    notifyListeners();
    return false;
  }
}

